service:
  name: monitoring-service

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:6200/service-monitoring-tool_db
    username: service-monitoring-tool_user
    password: service-monitoring-tool_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto : update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
        default-topic: monitoring-events
