spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: monitoring-service-group

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.Map
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:6200/service-monitoring-tool_db
    username: service-monitoring-tool_user
    password: service-monitoring-tool_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto : update