spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: monitoring-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:6200/service-monitoring-tool_db
    username: service-monitoring-tool_user
    password: service-monitoring-tool_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto : update